In [1]:
import numpy as np

a=np.array([20,30,40])
b=np.array([40,50,60])
print(a)
print(b)
print("add",a+b)
print("sub",a-b)
print("pro",a*b)

[20 30 40]
[40 50 60]
add [ 60  80 100]
sub [-20 -20 -20]
pro [ 800 1500 2400]


In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [4]:
import numpy as np

a=np.array([10,20,30])
b=np.array([40,50,60])
c=np.array([70,80,90])
print(a)
print(b)
print(c)
print(a+b+c)
print(a-b-c)
print(a*b*c)
print(a/b/c)

[10 20 30]
[40 50 60]
[70 80 90]
[120 150 180]
[-100 -110 -120]
[ 28000  80000 162000]
[0.00357143 0.005      0.00555556]


In [5]:
a=np.array(["usman","umar","asma"])
b=np.array(["10","20","30"])
print(a)
print(b)

['usman' 'umar' 'asma']
['10' '20' '30']


In [6]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 6 7]
[-3 -2 -1]
[ 4  8 12]
[0.25 0.5  0.75]


In [10]:
import numpy as np
a=np.array(["usman","umar","asma"])
b=np.array(["hasan","zubair","ayesha"])
print(a)
print(b)

['usman' 'umar' 'asma']
['hasan' 'zubair' 'ayesha']


In [12]:
import numpy as np
a=np.array([10,20,30])
b=np.array([10.5,20.5,30.5])
print(a)
print(b)
print(a+b)

[10 20 30]
[10.5 20.5 30.5]
[20.5 40.5 60.5]


In [13]:
l=[[10,20],[30,40,50]]
print(l)

[[10, 20], [30, 40, 50]]


In [14]:
l=[[10,20],[30,40],[50,60]]
print(l)

[[10, 20], [30, 40], [50, 60]]


In [17]:
import numpy as np
a=np.array([[10,20],[30,40],[50,60]])
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [18]:
import numpy as np
b=np.array([[1,2,3,4,5],[3,5,4,5,6]])
print(b)

[[1 2 3 4 5]
 [3 5 4 5 6]]


In [20]:
import numpy as np
arr=np.array([10,20,30])
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
arr=np.array([10,20,30])
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


In [24]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[90,100,10,20]])
print(arr)
print("type",type(arr))

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100  10  20]]
type <class 'numpy.ndarray'>


In [25]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
<class 'numpy.ndarray'>


In [59]:
#slicing
import numpy as np
arr=np.array([10,20,30,40])
print(arr[0:1])
print(arr[0:2])
print(arr[0:3])
print(arr[0:4])
print(arr[1:1])
print(arr[1:2])
print(arr[1:3])
print(arr[1:4])
print(arr[2:0])
print(arr[2:1])
print(arr[2:2])
print(arr[2:3])
print(arr[3:3])
print(arr[0:])
print(arr[1:])
print(arr[2:])
print(arr[3:])
print("type",type(arr))
print("Shape of array",np.shape(arr))
print("Size of array",np.size(arr))
print("dimension of array",np.ndim(arr))
print(arr.dtype)

[10]
[10 20]
[10 20 30]
[10 20 30 40]
[]
[20]
[20 30]
[20 30 40]
[]
[]
[]
[30]
[]
[10 20 30 40]
[20 30 40]
[30 40]
[40]
type <class 'numpy.ndarray'>
Shape of array (4,)
Size of array 4
dimension of array 1
int32


In [61]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0:1])
print(arr[0:2])
print(arr[0:3])
print(arr[0:])
print(arr[1:])
print(arr[2:])
print(arr[3:])
print(arr[2:3])
print(arr[:1])
print(arr[:2])
print(arr[:3])
print(arr[:4])
print(type(arr))
print("shape of array",np.shape(arr))
print("size of array",np.size(arr))
print("dimension of array",np.ndim(arr))
print(arr.dtype)

[1]
[1 2]
[1 2 3]
[1 2 3 4]
[2 3 4]
[3 4]
[4]
[3]
[1]
[1 2]
[1 2 3]
[1 2 3 4]
<class 'numpy.ndarray'>
shape of array (4,)
size of array 4
dimension of array 1
int32


In [75]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,0:1])
print()
print(arr[0:2,0:2])
print()
print(arr[0:3,0:3])
print()
print(arr[0:4,0:4])
print()
print(arr[0:5,0:5])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

[[1]]

[[1 2]
 [6 7]]

[[1 2 3]
 [6 7 8]]

[[1 2 3 4]
 [6 7 8 9]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
10
2
int32


In [79]:
import numpy as np
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0:1,0:1])
print(arr[0:2,0:2])
print(arr[0:3,0:3])
print(arr[0:4,0:4])
print(arr[0:5,0:5])
print()
print(arr[1:2,1:2])
print()
print(arr[1:3,1:3])
print()
print(arr[1:4,1:4])
print()
print(arr[1:5,1:5])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

[[10]]
[[10 20]
 [60 70]]
[[10 20 30]
 [60 70 80]]
[[10 20 30 40]
 [60 70 80 90]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

[[70]]

[[70 80]]

[[70 80 90]]

[[ 70  80  90 100]]
(2, 5)
10
2
int32


In [91]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,2:3])
print(arr[0,2:4])
print(arr[1,2:3])
print(arr[1,2:4])
print(arr[0,0:])
print(arr[0,1:])
print(arr[1,0:])
print(arr[1,1:])
print(arr[1,2:])
print(arr[1,3:])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

[3]
[3 4]
[7]
[7 8]
[1 2 3 4]
[2 3 4]
[5 6 7 8]
[6 7 8]
[7 8]
[8]
(2, 4)
8
2
int32


In [103]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.array(arr))
print()
print(arr[0,0:])
print(arr[0,1:])
print(arr[0,2:])
print(arr[0,3:])
print()
print(arr[1,0:])
print(arr[1,1:])
print(arr[1,2:])
print(arr[1,3:])
print()
print(arr[2,0:])
print(arr[2,1:])
print(arr[2,2:])
print(arr[2,3:])
print()
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]
[2 3 4]
[3 4]
[4]

[5 6 7 8]
[6 7 8]
[7 8]
[8]

[ 9 10 11 12]
[10 11 12]
[11 12]
[12]

(3, 4)
12
2
int32


In [121]:
import numpy as np
a=[10,20,30,40,50]
arr=np.array(a)
print(arr)
print()
print(len(a))
print(len(arr))
print()
print(arr.shape)
print(np.shape(arr))
print()
print(arr.size)
print(np.size(arr))
print()
print(type(arr))
print(type(a))
print()
print(arr.dtype)
print(arr.astype(int))
print(arr.astype(float))
print(arr.astype(str))
print()
print(arr.astype(int))
print(arr.astype(str))
print(arr.astype(float))
print()
print(arr.astype(str))
print(arr.astype(int))
print(arr.astype(float))

[10 20 30 40 50]

5
5

(5,)
(5,)

5
5

<class 'numpy.ndarray'>
<class 'list'>

int32
[10 20 30 40 50]
[10. 20. 30. 40. 50.]
['10' '20' '30' '40' '50']

[10 20 30 40 50]
['10' '20' '30' '40' '50']
[10. 20. 30. 40. 50.]

['10' '20' '30' '40' '50']
[10 20 30 40 50]
[10. 20. 30. 40. 50.]


In [132]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(np.shape(arr))
print()
print(arr.size)
print(np.size(arr))
print()
print(arr.ndim)
print(np.ndim(arr))
print()
print(type(arr))
print(arr.dtype)
print(len(arr))
print()
print(arr.astype(str))
print(arr.astype(int))
print(arr.astype(float))

(2, 3)
(2, 3)

6
6

2
2

<class 'numpy.ndarray'>
int32
2

[['1' '2' '3']
 ['4' '5' '6']]
[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [142]:
import numpy as np
arr=np.array([[12,34,55,66],[34,56,34,55]])
print(arr)
print(len(arr))
print()
print(arr.shape)
print(np.shape(arr))
print()
print(arr.size)
print(np.size(arr))
print()
print(arr.ndim)
print(np.ndim(arr))
print()
print(type(arr))
print(arr.dtype)
print()
print(arr.astype(str))
print(arr.astype(int))
print(arr.astype(float))

[[12 34 55 66]
 [34 56 34 55]]
2

(2, 4)
(2, 4)

8
8

2
2

<class 'numpy.ndarray'>
int32

[['12' '34' '55' '66']
 ['34' '56' '34' '55']]
[[12 34 55 66]
 [34 56 34 55]]
[[12. 34. 55. 66.]
 [34. 56. 34. 55.]]


In [143]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 7  9 11 13 15]
[ 7  9 11 13 15]


In [3]:
import numpy as np
arr1=np.array([1,3,5,7,11])
arr2=np.array([2,4,6,8,10])
arr3=np.array([1,3,5,7,9])
print(arr1+arr2+arr3)
print(np.add(arr1,arr2,arr3))

[ 4 10 16 22 30]
[ 3  7 11 15 21]


In [5]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]


In [6]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [9]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [11]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 1  4  9 16]


In [13]:
import numpy as np
arr1=np.array([1,2,4,5,6])
arr2=np.array([4])
print(np.power(arr1,arr2))

[   1   16  256  625 1296]


In [14]:
import numpy as np
arr1=np.array([2,4,6,8,10])
arr2=np.array([4])
print(np.power(arr1,arr2))

[   16   256  1296  4096 10000]


In [15]:
import numpy as np
arr1=np.array([2,4,6,8,10])
print(np.sqrt(arr1))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [16]:
import numpy as np
arr1=np.array([1,4,9,16,25])
print(np.sqrt(arr1))

[1. 2. 3. 4. 5.]


In [17]:
import numpy as np
arr1=np.array([1,4,9,16,25,36,49,64,81,100])
print(np.sqrt(arr1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
#Concatenate
a=[10,20,30,40]
b=[10,20,30,40]
print(a+b)

[10, 20, 30, 40, 10, 20, 30, 40]


In [21]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(np.concatenate([arr1,arr2]))

[10 20 30 40 50 60 70 80]


In [23]:
import numpy as np
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(np.concatenate([arr1,arr2]))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [24]:
arr1=np.array(["A","B","C","D"])
arr2=np.array(["E","F","G","H"])
print(np.concatenate([arr1,arr2]))

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']


In [27]:
arr1=np.array(["usman","umar","asma"])
arr2=np.array(["ibrahim","samra"])
print(np.concatenate([arr1,arr2]))

['usman' 'umar' 'asma' 'ibrahim' 'samra']


In [28]:
arr1=np.array(["usman","umar","asma"])
arr2=np.array(["ibrahim","samra"])
arr3=np.array(["amber","shan"])
print(np.concatenate([arr1,arr2,arr3]))

['usman' 'umar' 'asma' 'ibrahim' 'samra' 'amber' 'shan']


In [32]:
import numpy as np
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(np.concatenate([arr1,arr2]))
print()
print(np.concatenate([arr1,arr2], axis=0))
print()
print(np.concatenate([arr1,arr2], axis=1))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]

[[10 20]
 [30 40]
 [50 60]
 [70 80]]

[[10 20 50 60]
 [30 40 70 80]]


In [40]:
import numpy as np
arr1=np.array([[23,45],[45,67],[56,78]])
arr2=np.array([[45,67],[32,54],[54,68]])
print(np.concatenate([arr1,arr2]))
print()
print(np.concatenate([arr1,arr2], axis=0))
print()
print(np.concatenate([arr1,arr2], axis=1))

[[23 45]
 [45 67]
 [56 78]
 [45 67]
 [32 54]
 [54 68]]

[[23 45]
 [45 67]
 [56 78]
 [45 67]
 [32 54]
 [54 68]]

[[23 45 45 67]
 [45 67 32 54]
 [56 78 54 68]]


In [42]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(np.hstack([arr1,arr2]))
print()
print(np.vstack([arr1,arr2]))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[70,80,90],[100,110,120]])
print(np.hstack([arr1,arr2]))
print()
print(np.vstack([arr1,arr2]))

[[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [47]:
#split
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.array_split(arr,2))
print(np.array_split(arr,3))
print(np.array_split(arr,4))

[array([10, 20, 30]), array([40, 50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30, 40]), array([50]), array([60])]


In [50]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.array_split(arr,2))
print(np.array_split(arr,3))
print(np.array_split(arr,4))
print(np.array_split(arr,5))

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]
[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]
[array([10, 20, 30]), array([40, 50, 60]), array([70, 80]), array([ 90, 100])]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100])]


In [53]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
arr1=np.array_split(arr,3)
print(arr[0])
print()
print(arr1[1])

[10 20 30]

[[40 50 60]]


In [54]:
import numpy as np
arr=np.array([[34,56,45,67],[34,78,56,79]])
arr1=np.array_split(arr,3)
print(arr1[0])
print()
print(arr1[1])

[[34 56 45 67]]

[[34 78 56 79]]


In [55]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1=np.array_split(arr,2)
print(arr1[0])
print()
print(arr1[1])

[[1 2 3 4 5]]

[[ 6  7  8  9 10]]


In [56]:
import numpy as np
arr=np.array([[1,3,5,7,9],[2,4,6,8,10]])
arr1=np.array_split(arr,2)
print(arr1[0])
print()
print(arr1[1])

[[1 3 5 7 9]]

[[ 2  4  6  8 10]]


In [1]:
import numpy as np
arr=np.array([[1,3,5,7,9],[2,4,6,8,10]])
arr1=np.array_split(arr,2)
print(arr1[0])
print(arr1[1])

[[1 3 5 7 9]]
[[ 2  4  6  8 10]]


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1=np.array_split(arr,2)
print(arr1[0])
print()
print(arr1[1])
print()

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]]



In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.array_split(arr,3),(arr[0]))
print()
print(np.array_split(arr,4),(arr[1]))
print()
print(np.array_split(arr,2),(arr[2]))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])] [1 2 3]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])] [4 5 6]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])] [7 8 9]


In [25]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(np.array_split(arr,1),"index of array",(arr[0],(arr[1])))
print()
print(np.array_split(arr,2),"index of array",(arr[1]))
print()
print(np.array_split(arr,3),"index of array",(arr[2]))
print()
print(np.array_split(arr,4),"index of array",(arr[3]))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])] index of array (array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])] index of array [ 6  7  8  9 10]

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])] index of array [11 12 13 14 15]

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])] index of array [16 17 18 19 20]


In [35]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.array_split(arr,1))
print()
print(np.array_split(arr,2))
print()
print(np.array_split(arr,3))
print()
print(np.array_split(arr,4))
print()
print(np.array_split(arr,1),(arr,2),(arr,3),(arr,4))

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])] (array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), 2) (array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), 3) (array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), 4)


In [36]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.append(arr,[6]))

[1 2 3 4 5 6]


In [41]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.append(arr,[8,9]))

[1 2 3 4 5 8 9]


In [42]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.append(arr,["usman","I"]))

['1' '2' '3' '4' '5' 'usman' 'I']


In [43]:
import numpy as np
arr=np.array([12,34,33,56])
print(np.insert(arr,2,35))

[12 34 35 33 56]


In [45]:
import numpy as np
arr=np.array([12,34,55,67])
print(np.insert(arr,2,34))

[12 34 34 55 67]


In [49]:
import numpy as np
arr=np.array([11,22,33,44])
print(np.insert(arr,1,12),np.insert(arr,3,67))

[11 12 22 33 44] [11 22 33 67 44]


In [50]:
import numpy as np
arr=np.array([12,34,32,34,56])
print(np.insert(arr,3,[11,12]))

[12 34 32 11 12 34 56]


In [52]:
import numpy as np
arr=np.array([11,12,33,45,66,77,88])
print(np.append(arr,[100,123]))
print(np.insert(arr,3,[12,21]))

[ 11  12  33  45  66  77  88 100 123]
[11 12 33 12 21 45 66 77 88]


In [54]:
import numpy as np
arr=np.array([[10,20],[43,45]])
print(np.insert(arr,2,[35,67], axis=0))
print()
print(np.insert(arr,2,[35,67], axis=1))

[[10 20]
 [43 45]
 [35 67]]

[[10 20 35]
 [43 45 67]]


In [68]:
import numpy as np
arr=np.array([[12,34,55,67],[45,87,98,32]])
print(np.insert(arr,2,[56,87,56,45], axis=0))
print()
print(np.insert(arr,2,[12,34], axis=1))

[[12 34 55 67]
 [45 87 98 32]
 [56 87 56 45]]

[[12 34 12 55 67]
 [45 87 34 98 32]]


In [4]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(np.insert(arr,2,[34,56], axis=1))

[[10 20 34 30]
 [40 50 56 60]]


In [16]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(np.insert(arr,2,[45,68], axis=0))
print()
print(np.insert(arr,2,[45,68], axis=1))

[[10 20]
 [30 40]
 [45 68]]

[[10 20 45]
 [30 40 68]]


In [19]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(np.insert(arr,2,[12,14], axis=1))
print()
print(np.insert(arr,4,[12,14], axis=1))

[[10 20 12 30 40]
 [50 60 14 70 80]]

[[10 20 30 40 12]
 [50 60 70 80 14]]


In [23]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(np.insert(arr,1,[15,25], axis=0))
print(np.insert(arr,1,[15,25], axis=1))
print()
print(np.insert(arr,2,[15,25], axis=0))
print(np.insert(arr,2,[15,25], axis=1))

[[10 20]
 [15 25]
 [30 40]]
[[10 15 20]
 [30 25 40]]

[[10 20]
 [30 40]
 [15 25]]
[[10 20 15]
 [30 40 25]]


In [28]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(np.insert(arr,2,[15,25], axis=1))

[[10 20 15 30]
 [40 50 25 60]]


In [31]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(np.insert(arr,1,[15,25], axis=1))
print(np.insert(arr,2,[15,25], axis=1))

[[10 15 20 30 40]
 [50 25 60 70 80]]
[[10 20 15 30 40]
 [50 60 25 70 80]]


In [33]:
import numpy as np
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(np.insert(arr,1,[15,25], axis=1))

[[ 10  15  20  30  40  50]
 [ 60  25  70  80  90 100]]


In [37]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(np.insert(arr,[1,2],[50], axis=0))
print()
print(np.insert(arr,[1,2],[50], axis=1))

[[10 20]
 [50 50]
 [30 40]
 [50 50]]

[[10 50 20 50]
 [30 50 40 50]]


In [51]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(np.insert(arr,[1,2,3],[50], axis=1))

[[10 50 20 50 30 50]
 [40 50 50 50 60 50]]


In [48]:
import numpy as np
arr=np.array([[10,20],[30,40],[50,60],[70,80]])
print(np.insert(arr,[1,2,3,4],[90], axis=0))

[[10 20]
 [90 90]
 [30 40]
 [90 90]
 [50 60]
 [90 90]
 [70 80]
 [90 90]]


In [49]:
import numpy as np
arr=np.array([[10,20],[30,40],[50,60]])
print(np.insert(arr,[1,2,3],[70], axis=0))

[[10 20]
 [70 70]
 [30 40]
 [70 70]
 [50 60]
 [70 70]]


In [55]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(np.delete(arr,0))
print(np.delete(arr,1))
print(np.delete(arr,2))
print(np.delete(arr,3))

[20 30 40]
[10 30 40]
[10 20 40]
[10 20 30]


In [56]:
import numpy as np
arr=np.array([[10,20],[30,40],[50,60]])
print(np.delete(arr,0))
print(np.delete(arr,1))
print(np.delete(arr,2))
print(np.delete(arr,3))
print(np.delete(arr,4))
print(np.delete(arr,5))

[20 30 40 50 60]
[10 30 40 50 60]
[10 20 40 50 60]
[10 20 30 50 60]
[10 20 30 40 60]
[10 20 30 40 50]


In [59]:
import numpy as np
arr=np.array([10,20])
print(np.delete(arr,[0,1]))

[]


In [63]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(np.delete(arr,[0,1]))
print(np.delete(arr,[0,1,2]))
print(np.delete(arr,[0,1,2,3]))

[30 40]
[40]
[]


In [71]:
import numpy as np
arr=np.array([[10,20],[30,40]])
print(np.delete(arr,0, axis = 0))
print(np.delete(arr,0, axis = 1))
print()
print(np.delete(arr,1, axis = 0))
print(np.delete(arr,1, axis = 1))

[[30 40]]
[[20]
 [40]]

[[10 20]]
[[10]
 [30]]


In [75]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(np.delete(arr,0, axis=0))
print(np.delete(arr,0, axis=1))
print()
print(np.delete(arr,1, axis=0))
print(np.delete(arr,1, axis=1))
print()
print(np.delete(arr,2, axis=1))
print(np.delete(arr,2, axis=1))

[[40 50 60]]
[[20 30]
 [50 60]]

[[10 20 30]]
[[10 30]
 [40 60]]

[[10 20]
 [40 50]]
[[10 20]
 [40 50]]


In [76]:
#sort
import numpy as np
arr=np.array([3,5,6,1,2,6,7])
print(np.sort(arr))

[1 2 3 5 6 6 7]


In [78]:
import numpy as np
arr=np.array([[2,4,1,6],[3,2,7,9]])
print(np.sort(arr))

[[1 2 4 6]
 [2 3 7 9]]


In [79]:
import numpy as np
arr=np.array([[7,5,2,3],[5,6,8,2],[3,6,5,1]])
print(np.sort(arr))

[[2 3 5 7]
 [2 5 6 8]
 [1 3 5 6]]


In [80]:
#search
arr=np.array([2,4,5,6,7])
print(np.where(arr==6))

(array([3], dtype=int64),)


In [81]:
import numpy as np
arr=np.array([2,4,6,5])
print(np.where(arr==4))

(array([1], dtype=int64),)


In [83]:
import numpy as np
arr=np.array([[3,1,4,6,4],[3,1,5,4,3]])
print(np.where(arr==6),np.where(arr==4))

(array([0], dtype=int64), array([3], dtype=int64)) (array([0, 0, 1], dtype=int64), array([2, 4, 3], dtype=int64))


In [3]:
import numpy as np
arr=np.array([2,6,3,1,9])
print(np.where(arr==[6]))

(array([1], dtype=int64),)


In [4]:
import numpy as np
arr=np.array([3,1,6,5,8,7])
print(np.where(arr==8))
print(np.sort(arr))

(array([4], dtype=int64),)
[1 3 5 6 7 8]


In [6]:
import numpy as np
arr=np.array(["usman","asad","hasan"])
print(np.where(arr==["asad"]))
print(np.sort(arr))

(array([1], dtype=int64),)
['asad' 'hasan' 'usman']


In [7]:
import numpy as np
arr=np.array([3,2,5,6,1,8,9,7])
print(np.searchsorted(arr,9))

6


In [8]:
import numpy as np
arr=np.array(["usman","umair","usama"])
print(np.searchsorted(arr,"umair"))

0


In [13]:
import numpy as np
arr=np.array([1,4,3,6,5,2])
print(np.sort(arr))
print(np.where(arr==2))
print(np.searchsorted(arr,2))

[1 2 3 4 5 6]
(array([5], dtype=int64),)
1


In [14]:
import numpy as np
arr=np.array([2,1,3,5,4,7,6])
print(np.searchsorted(arr,4))

3


In [15]:
import numpy as np
arr=np.array([1,2,3,2,4,5])
print(np.searchsorted(arr,2))

1


In [22]:
#filter
import numpy as np
arr=np.array([1,2,3,4,5,6])
fil=[False,True,False,True,False,True]
new=arr[fil]
print("even no",new)

even no [2 4 6]


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
fil=[True,False,True,False,True,False]
new=arr[fil]
print("odd no",new)

odd no [1 3 5]


In [20]:
import numpy as np
arr=np.array(["usman","asad","zain","kashan"])
fil=[True,False,True,False]
new=arr[fil]
print(new)

['usman' 'zain']


In [23]:
import numpy as np
arr=np.array([12,34,54,67,87])
fa=arr>50
print(fa)

[False False  True  True  True]


In [24]:
import numpy as np
arr=np.array([10,20,30,40,50,67,88])
fil=arr>50
print(fil)

[False False False False False  True  True]


In [26]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
fil=arr<50
fil1=arr>50
print(fil)
print(fil1)

[ True  True  True  True False False]
[False False False False False  True]


In [30]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80])
fil=arr>30
fil1=arr<70
print(fil)
print(fil1)

[False False False  True  True  True  True  True]
[ True  True  True  True  True  True False False]


In [31]:
import numpy as np
arr=np.array([10,12,33,45,67])
fil=arr>33
new_array=arr[fil]
print(new_array)

[45 67]


In [32]:
import numpy as np
arr=np.array([10,9,34,23,67,98,87,56])
fil=arr>50
new_array=arr[fil]
print(new_array)

[67 98 87 56]


In [34]:
import numpy as np
arr=np.array([10,9,96,23,67,98,87,56])
fil=arr<50
new_array=arr[fil]
print(new_array)

[10  9 23]


In [37]:
import numpy as np
arr=np.array([12,13,1,2,44,56,67,89])
fil=arr % 2==0
new_array=arr[fil]
print(new_array)

[12  2 44 56]


In [39]:
import numpy as np
arr=np.array([12,13,44,45,66,78,77])
fil=arr % 2!=0
new_array=arr[fil]
print(new_array)

[13 45 77]


In [40]:
import numpy as np
arr=np.array([11,12,43,56,11,55,67,88])
fil=arr % 2==1
new_array=arr[fil]
print(new_array)

[11 43 11 55 67]


In [41]:
import numpy as np
arr=np.array([11,12,43,56,11,55,67,88])
fil=arr % 2!=1
new_array=arr[fil]
print(new_array)

[12 56 88]


In [11]:
#Aggregative functions
import numpy as np
arr=np.array([10,20,30,40,50,50,60])
print("sum",np.sum(arr))
print("diff",np.diff(arr))
print("max",np.max(arr))
print("min",np.min(arr))
print("count",np.size(arr))
print("mean",np.mean(arr))
print("median",np.median(arr))
print("cumilative sum",np.cumsum(arr))
print("cumilative product",np.cumprod(arr))

sum 260
diff [10 10 10 10  0 10]
max 60
min 10
count 7
mean 37.142857142857146
median 40.0
cumilative sum [ 10  30  60 100 150 200 260]
cumilative product [        10        200       6000     240000   12000000  600000000
 1640261632]


In [22]:
import numpy as np
import statistics as stats
arr=np.array([1,2,3,4,5,6,7,8,9,10,2])
print("sum",np.sum(arr))
print("diff",np.diff(arr))
print("product",np.prod(arr))
print("mean",np.mean(arr))
print("median",np.median(arr))
print("mode",stats.mode(arr))
print("varience",np.var(arr))
print("standard deviation",np.std(arr))
print("cumilative sum",np.cumsum(arr))
print("cumilative product",np.cumprod(arr))

sum 57
diff [ 1  1  1  1  1  1  1  1  1 -8]
product 7257600
mean 5.181818181818182
median 5.0
mode 2
varience 8.512396694214877
standard deviation 2.9176011883420387
cumilative sum [ 1  3  6 10 15 21 28 36 45 55 57]
cumilative product [      1       2       6      24     120     720    5040   40320  362880
 3628800 7257600]


In [33]:
arr=np.array([100,150,200,250,300])
arr1=np.array([20,30,40,50,60])

price=np.array(arr)
quantity=np.array(arr1)

print("total price",np.sum(price))
print("total quantity",np.sum(quantity))

print("price :",price,"\n","quantity :",quantity)
print()
print(np.cumprod([price,quantity], axis=0))
print()
c=np.cumprod([price,quantity], axis=0)
print(c[1].sum())

total price 1000
total quantity 200
price : [100 150 200 250 300] 
 quantity : [20 30 40 50 60]

[[  100   150   200   250   300]
 [ 2000  4500  8000 12500 18000]]

45000


In [43]:
arr=np.array([1000,2000,3000,40000])
arr1=np.array([20,40,60,80])

price=np.array(arr)
quantity=np.array(arr1)

print("total price",np.sum(price))
print("total quantity",np.sum(quantity))

print("price",price,"\n","quantity",quantity)
print()
print(np.cumprod([price,quantity], axis=0))
c=np.cumprod([price,quantity], axis=0)
print(c[0].sum())
print(c[1].sum())

total price 46000
total quantity 200
price [ 1000  2000  3000 40000] 
 quantity [20 40 60 80]

[[   1000    2000    3000   40000]
 [  20000   80000  180000 3200000]]
46000
3480000


In [52]:
arr=np.array([100,200,300,400,500])
arr1=np.array([10,20,30,40,50])

price=np.array(arr)
quantity=np.array(arr1)

print("price",price, "\n", "quantity",quantity)
print()
print(np.cumprod([price,quantity], axis=0))
a=np.cumprod([price,quantity], axis=0)
print(c[0].sum())
print(c[1].sum())

price [100 200 300 400 500] 
 quantity [10 20 30 40 50]

[[  100   200   300   400   500]
 [ 1000  4000  9000 16000 25000]]
46000
3480000


In [53]:
a=[10,20,30,40,50]
b=[5,10,15,20,25]
print(np.corrcoef([a,b]))

[[1. 1.]
 [1. 1.]]


In [54]:
a=[20,23,45,67,98]
b=[45,66,78,87,90]
c=[21,65,34,76,87]
print(np.corrcoef([a,b,c]))

[[1.         0.86171567 0.75025392]
 [0.86171567 1.         0.78457825]
 [0.75025392 0.78457825 1.        ]]


In [55]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[11,12,13,14,15]
print(np.corrcoef([a,b,c]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
price=[100,200,300,400]
quantity=[5,10,15,20]

print(np.cumprod([price,quantity], axis=0))
a=np.cumprod([price,quantity], axis=0)
print(a[0].sum())
print(a[1].sum())

[[ 100  200  300  400]
 [ 500 2000 4500 8000]]
1000
15000
